### ISSUE TITLE
对部署流程增加日志功能，类似于Jenkins的部署日志

### ISSUE THREAD

**Issue by PineappleLB** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#1]
针对需求可以是简单的部署记录直接保存到本地

也可以保存到线上阿里云的某日志服务中，貌似目前的日志功能就是保存到那里的，只是还没法使用

其实需求第一步就是可以保留日志仅此而已

**Comment by KaihangXing** [comment]
你好，目前已经支持用sls记录部署 Host / ECS 的日志，在 Run 中进行配置
![20210705235056](https://user-images.githubusercontent.com/39126217/124496430-fc026300-ddeb-11eb-822b-24bfe7a5c236.jpg)
