### ISSUE TITLE
IDEA 运行时有插件的报错信息

### ISSUE THREAD

**Issue by f1ynnzhan9** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#11]
**Bug描述**
IDEA 运行时无规律出现插件的报错信息（应该是某些操作导致的，但目前尚未甄别是哪些操作），请参见截图。

**复现路径**
无

**期望的行为**
IDEA 运行时没有插件的报错信息。

**截图**
![image](https://user-images.githubusercontent.com/80672942/129011544-f0220636-2330-4b6d-82c7-28c3815714d8.png)
![image](https://user-images.githubusercontent.com/80672942/129011554-26f7b6ca-46fd-4fb7-9394-990be3ddae80.png)

**运行环境**
- 操作系统: Windows 10 专业工作站版 21H1 19043.1110
- JetBrains 产品类型: Ultimate Edition
- JetBrains 产品版本: IntelliJ IDEA 2021.2
- Cloud Toolkit 版本: 2021.8.1-212

**附加上下文**
无

**Comment by f1ynnzhan9** [comment]
目前发现一个明显的时机：通过 IDEA 创建新项目时，会触发插件报错。

**Comment by KaihangXing** [comment]
2021.9.1 版本修复
