### ISSUE TITLE
Tookit插件代码评审功能bug

### ISSUE THREAD

**Issue by yzzcyh** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#15]
**Bug描述**
Tookit插件代码评审功能bug：
1. 发起评审后不可修改评审
2. 评审人也无法通过插件完成评审

同样的参数，在webstorm中，一切正常

**复现路径**
1. ....发起代码评审后，找到评审中状态
2. ....右键，修改评审等所有选项全部不可用
3. ....评审员，评审所有选项也不可用
4. ....

**期望的行为**
发起评审后，可对评审进行修改

**截图**
![image](https://user-images.githubusercontent.com/4386606/132089389-a7faff7f-600f-462e-ab40-8a111dcd75de.png)

![image](https://user-images.githubusercontent.com/4386606/132089404-577d9943-47ed-4db0-824f-a8c31ae709f4.png)

**运行环境**
- 操作系统: macOS Big Sur11.5.2
- JetBrains 产品类型:IDEA
- JetBrains 产品版本:2021.2
- Cloud Toolkit 版本:2021.8.1-212

**附加上下文*
同样的操作，在webstorm中没有发现这个问题

**Comment by KaihangXing** [comment]
问题已定位到，将在12月发布的版本中修复
