### ISSUE TITLE
插件无法启动

### ISSUE THREAD

**Issue by seraphapple** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#17]
**Bug描述**
![错误](https://user-images.githubusercontent.com/17469663/136727330-a666ead2-202b-4119-aa99-35ef0599f1d2.png)
在idea上安装alibaba-cloud-toolkit插件，安装好重启无法启动插件，报错如图

**复现路径**
在idea上安装alibaba-cloud-toolkit插件，安装好重启

**期望的行为**
正常启动可以运行插件

**截图**

**运行环境**
1. idea版本号
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
Licensed to tbtx

JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

2. 项目的jdk已改成11， java complier也改成了jdk 11

**Comment by KaihangXing** [comment]
插件需要 IDEA 用 JDK11 进行启动（注意：不是IDEA启动后，工程使用的JDK版本），可以升一下 IDEA 的版本到 2021.2 版本，或者重装一下 IDEA，使用带 JRE11 的版本

![image](https://user-images.githubusercontent.com/39126217/136731259-3f43a248-b3be-49c4-ab72-96ea7107ec8b.png)
