### ISSUE TITLE
jar 包上传之后的命令没有执行

### ISSUE THREAD

**Issue by j2wyatt** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#2]
jar 包上传之后的命令没有执行

**基本描述**
1. 使用 host 部署方式
2. 使用 maven 构建部署文件
3. jar 包正常上传
4. after 命令没有执行

**期望的行为**
希望能正常执行命令

**截图**
<img width="1167" alt="截屏" src="https://user-images.githubusercontent.com/53614528/123051822-b54c5a80-d434-11eb-91b8-85d0c019b448.png">

**运行环境**
- 操作系统: mac BigSur 11.4
- JetBrains : IntelliJ IDEA 2020.1.2 (Ultimate Edition)
- Cloud Toolkit 版本: 2021.4.1

**Comment by KaihangXing** [comment]
pkill 问题导致的，先close 了
