### ISSUE TITLE
通过复制得到部署配置，在重启 IDEA/项目后消失了

### ISSUE THREAD

**Issue by f1ynnzhan9** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#4]
**Bug描述**
通过复制得到部署配置，在重启 IDEA/项目后消失了。
注意：只是复制的配置会消失，新增的不会消失。

**复现路径**
例如现有一份部署配置【Deploy to 测试】。
复制了一份【Deploy to 测试】的部署配置，
重命名为【Deploy to 开发】，保存配置信息，
重启 IDEA/项目后，【Deploy to 开发】配置就不见了。

**期望的行为**
重启后，复制的配置能保留下来。

**截图**
![image](https://user-images.githubusercontent.com/80672942/123910111-9279f300-d9ac-11eb-98b8-6e89a463d135.png)

**运行环境**
- 操作系统: Windows 10 专业工作站版 20H2 19042.1081
- JetBrains 产品类型: Ultimate Edition
- JetBrains 产品版本: IntelliJ IDEA 2021.1.2
- Cloud Toolkit 版本: 2021.4.1

**附加上下文**
无

**Comment by f1ynnzhan9** [comment]
原配置和复制的配置全改成纯英文，重启后保留下来了，但是之前消失的配置（中文命名）也突然出现了，而且删除了好几次才完全删掉（删掉这些配置，重启 IDEA，结果被删除的配置大部分回来了，一遍遍删除-重启，好多遍之后才全删完）。

**Comment by KaihangXing** [comment]
windows 环境下，Run 配置名称是中文导致的，可以通过把名称改为英文暂时规避掉。

我们在Windows环境下没有复现这个问题，怀疑跟本地的某些配置有关系。如果需要我们配合进一步排查，请提供**出现问题时**的 **Run 配置截图**，以及**当前工程 .idea/workspace.xml 文件中 name="RunManager" 的 <component> </component> 部分配置文件代码**（请检查确保没有敏感信息）
