### ISSUE TITLE
当操作系统用户目录不是在/home下时，使用idea 插件安装arthas 报错

### ISSUE THREAD

**Issue by wangtaicheng** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#6]
**Bug描述**
当操作系统用户目录不是在/home下时，使用idea 插件安装arthas 报错

**复现路径**
1. 操作系统中新建用户 `useradd  -d /data/web -s /bin/bash web`
2. 点击idea  alibaba cloud view ->more->Diagnostic

**期望的行为**
能够正常安装arthas 并能启动

**截图**
![image](https://user-images.githubusercontent.com/6257526/126087163-949b864d-2a27-4902-9fc9-27b12907800f.png)
![image](https://user-images.githubusercontent.com/6257526/126087087-d42707fb-0dff-42e2-866b-aadda30ec1f8.png)
![image](https://user-images.githubusercontent.com/6257526/126087070-7406dae9-5705-4595-99b1-c0dc84aee244.png)

**运行环境**
- 操作系统:  Windows 10 10.0
- JetBrains 产品类型: idea 
- JetBrains 产品版本: Build #IU-211.7628.21, built on June 30, 2021
- Cloud Toolkit 版本: 2021.7.1-211

**附加上下文*

**Comment by KaihangXing** [comment]
2021.9.1 版本修复

**Comment by wangtaicheng** [comment]
> 2021.9.1 版本修复

![image](https://user-images.githubusercontent.com/6257526/134265022-539a57e5-2ff7-4dbc-a21f-bbbd9bf3ae2b.png)
![image](https://user-images.githubusercontent.com/6257526/134265055-991336e1-1ad1-4858-8f5c-34adfc18536d.png)
![image](https://user-images.githubusercontent.com/6257526/134265092-335c3f31-cf05-436f-b9fc-23deb61b2d34.png)
依然不可用
