### ISSUE TITLE
需要类似正则的配置能批量选中文件

### ISSUE THREAD

**Issue by 18855532268** [alibaba-cloud-toolkit/cloud-toolkit-jetbrains#7]
**您的功能请求是否与问题有关？ 请描述**
![image](https://user-images.githubusercontent.com/57880679/126439625-08e39dcd-f8f0-411a-9b94-51a4966eeb02.png)

每次发布版本文件名都会相应改动，而相应的需要每次发布都需要修改选中的文件名，不然会找不到文件

**描述您想要的解决方案**
需要类似正则的配置能批量选中文件或者其他更灵活的方案

**附加上下文**
钉钉：yaobuyang

姚步阳: 可以问大佬们一个问题吗

这个File可以获取指定类型的文件吗

姚步阳: [图片]
别象: 指定类型是什么意思？你选中哪个文件，就上传哪个文件@姚步阳 
姚步阳: 但是版本号是写死了，每次发布的话需要去文件里面修改一下版本号才能获取到文件
姚步阳: [图片]
别象: @姚步阳 是需要类似正则的配置能批量选中文件吗？
姚步阳: 是的
别象: @姚步阳 目前是不支持的。https://github.com/alibaba-cloud-toolkit/cloud-toolkit-vscode/issues   您可以在这里提一下issue，我们会评估一下需求，然后做排期
别象: @姚步阳 issue中备注下钉钉号，也可以加一些聊天记录截图，我们解决并发布后，会通知到你

希望各位大佬能够救救孩子

**Comment by KaihangXing** [comment]
已沟通，推荐使用maven build的方式，再加上 maven assembly plugin ，可以打包多个指定的文件或目录，一起上传到服务器
